version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      args:
        APP_USER: node
    image: app_frontend_dev
    container_name: app_frontend_dev
    command: npm run development
