version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Copy deploy script to droplet
          command: scp ./deploy/production.http.sh $DROPLET_USER@$DROPLET_IP:/home/$DROPLET_USER
      - run:
          name: Execute deploy script on droplet
          command: ssh $DROPLET_USER@$DROPLET_IP "/home/$DROPLET_USER/production.http.sh"
