version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: SSH into droplet
          command: ssh -oStrictHostKeyChecking=no \
          -v $DROPLET_USER@$DROPLET_IP “./deploy_project.sh”
      - run:
          name: Checkout repository
          command: |
            cd /var/www/
            if [[ ! -d "/var/www/project-personal-portfolio" ]]; then
              git clone git@github.com:GabrielDCelery/project-personal-portfolio.git
            fi
            cd project-personal-portfolio
            git pull
      - run:
          name: Deploy
          command: make prod-http
