version: '3'
services:
  frontend:
    build:
      context: ../app/frontend
      dockerfile: Dockerfile
      args:
        APP_USER: root
    image: app_frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    command: npm run start
    environment:
      FRONTEND_APP_PORT: 3000
  reverse_proxy:
    image: nginx
    container_name: app_reverse_proxy
    depends_on:
      - frontend
    volumes:
      - ../app/reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
